/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'channelName' : IDL.Text,
  'category' : IDL.Text,
  'videoId' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearChatHistory' : IDL.Func([], [], []),
  'getAllFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'searchVideosByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'channelName' : IDL.Text,
    'category' : IDL.Text,
    'videoId' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearChatHistory' : IDL.Func([], [], []),
    'getAllFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'searchVideosByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };