/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export type MessageId = bigint;
export interface Post {
  'id' : PostId,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
}
export type PostId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'clearChatHistory' : ActorMethod<[], undefined>,
  'createPost' : ActorMethod<[string, string], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllPreferences' : ActorMethod<[], Array<[string, string]>>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getLikedPostsByUser' : ActorMethod<[Principal], Array<PostId>>,
  'getPreference' : ActorMethod<[string], [] | [string]>,
  'hasUserLikedPost' : ActorMethod<[Principal, PostId], boolean>,
  'sendMessage' : ActorMethod<[string], ChatMessage>,
  'setPreference' : ActorMethod<[string, string], undefined>,
  'toggleLikePost' : ActorMethod<[PostId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];