/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const MessageId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearChatHistory' : IDL.Func([], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllPreferences' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getLikedPostsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PostId)],
      ['query'],
    ),
  'getPreference' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'hasUserLikedPost' : IDL.Func([IDL.Principal, PostId], [IDL.Bool], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'setPreference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleLikePost' : IDL.Func([PostId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const MessageId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearChatHistory' : IDL.Func([], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllPreferences' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getLikedPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostId)],
        ['query'],
      ),
    'getPreference' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'hasUserLikedPost' : IDL.Func(
        [IDL.Principal, PostId],
        [IDL.Bool],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'setPreference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleLikePost' : IDL.Func([PostId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };